dependencies {
    api "com.hazelcast:hazelcast-zookeeper:4.0.2"
    api "com.hazelcast:hazelcast:5.2.1"
    runtimeOnly("commons-logging:commons-logging:1.3.5")

    api "org.apache.curator:curator-x-discovery:5.8.0"
    testImplementation "org.apache.curator:curator-test:5.8.0"

    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.8.2")
}
