apiVersion: apps/v1
kind: Deployment
metadata:
  name: eu-translate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eu-translate
  template:
    metadata:
      labels:
        app: eu-translate
    spec:
      containers:
        - name: eu-translate
          image: localhost:5000/eu-translate:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_URL
              # service name
              value: "http://eureka:8761/eureka/"
#            - name: SPRING_APPLICATION_NAME
#              value: "eu-translate"
            - name: SERVER_PORT
              value: "8080"
