
dependencies {
    api "io.kubernetes:client-java:26.0.0"
//    implementation "com.fasterxml.jackson.core:jackson-databind:2.18.4"

    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
    implementation "org.junit.jupiter:junit-jupiter-params:${junitJupiterVersion}"
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")
}

