import com.bmuschko.gradle.docker.tasks.image.*
import org.codehaus.groovy.runtime.GStringImpl

dependencies {
    implementation 'io.etcd:jetcd-core:0.8.6'
    implementation "com.fasterxml.jackson.core:jackson-databind:2.18.4"

    runtimeOnly "ch.qos.logback:logback-classic:1.5.21" // logging

    testImplementation "org.testcontainers:testcontainers-toxiproxy:${testContainersVersion}"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:${testContainersVersion}"
    testImplementation "org.testcontainers:testcontainers:${testContainersVersion}"
    testImplementation("io.etcd:jetcd-launcher:0.8.6")

//    implementation platform('org.testcontainers:testcontainers-bom:2.0.2') //import bom
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")
}

containerImage = "localhost:5000/etcd-sandbox:latest"
containerPorts = ["7777:7777"]
containerEnv = [
        "ETCD_ENDPOINT": "http://vk-etcd:2379",
]

task createDockerfile(type: Dockerfile) {
    dependsOn jar

    from 'openjdk:17-jdk-alpine'

    copyFile 'app.jar', '/app/app.jar'
    copyFile 'libs', '/app/libs'

    workingDir '/app'
    entryPoint 'java', '-cp', 'app.jar:libs/*', 'vk.vkPets.server.Node', 'container-mode'
}

task prepareDockerContext(type: Copy) {
    dependsOn jar

    from("$buildDir/libs") {
        include "*.jar"
        rename { "app.jar" }
    }

    from(configurations.runtimeClasspath) {
        into "libs"
    }

    into("$buildDir/docker")
}

tasks.named('buildDockerImage', DockerBuildImage) {
    dependsOn createDockerfile, prepareDockerContext
    inputDir = file("$buildDir/docker")
    images.add("${project.containerImage}")
}
