
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

plugins {
    id 'org.springframework.boot'
    id 'com.bmuschko.docker-remote-api'  version '9.4.0'
}
//apply from: '../../docker.gradle'

tasks.register('buildEurekaImages') {
    dependsOn "eurekaSpace:eureka:buildDockerImage"
    dependsOn "eurekaSpace:eu-main:buildDockerImage"
    dependsOn "eurekaSpace:eu-translate:buildDockerImage"
}

tasks.register('buildZkImages') {
    dependsOn ":zk-hello:buildDockerImage"
    dependsOn ":zk-foo:buildDockerImage"
}

tasks.register('buildConsulImages') {
    dependsOn ":consul-hello:buildDockerImage"
    dependsOn ":consul-foo:buildDockerImage"
}

allprojects {
    group = 'vk.vkPets'
    version = '0.0.1'

    repositories {
        mavenLocal()
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'idea'
    apply plugin: 'com.bmuschko.docker-remote-api'
//    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    dependencies {
        compileOnly 'org.jetbrains:annotations:19.0.0'
        testCompileOnly 'org.jetbrains:annotations:19.0.0'
    }

    test {
        useJUnitPlatform()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }

    def containerNetwork = "vkcloud-manual-network" // must be created via "docker network create <NAME>"
    ext.containerName = "${project.name}"
    ext.containerImage = "${ext.containerName}:latest"
    ext.containerPorts = []   // Default empty, overridden in subprojects
    ext.containerEnv = [:]   // environment variables

    tasks.register('buildDockerImage', com.bmuschko.gradle.docker.tasks.image.DockerBuildImage) {
        dependsOn build       // make sure the JAR exists
        inputDir = project.projectDir
        images.add("${project.containerImage}")
    }

    // pushes image to docker registry
    tasks.register('pushDockerImage', com.bmuschko.gradle.docker.tasks.image.DockerPushImage) {
        dependsOn buildDockerImage
        images.add("localhost:5000/${project.containerImage}")
    }

    tasks.register('saveImage', com.bmuschko.gradle.docker.tasks.image.DockerSaveImage) {
        dependsOn buildDockerImage
        images.add("${project.containerName}:latest")
        destFile = file("$buildDir/${project.containerName}.tar")
    }

    // exec before run: export SUDO_PASS="your-password"
    tasks.register('importImageToK3s', Exec) {
        dependsOn tasks.named('saveImage')

        def sudoPass = System.getenv("SUDO_PASS")
        if (!sudoPass) {
            throw new GradleException("SUDO_PASS environment variable is not set. Exec 'export SUDO_PASS=...'")
        }

        commandLine "bash", "-c", "echo ${sudoPass} | sudo -S k3s ctr images import $buildDir/${project.containerName}.tar"
    }

    tasks.register('createContainer', com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer) {
        dependsOn tasks.named('buildDockerImage')
        targetImageId project.containerImage
        containerName = project.containerName
        hostConfig.portBindings = project.containerPorts
        hostConfig.network = containerNetwork
        envVars = project.containerEnv
    }

    tasks.register('startContainer', com.bmuschko.gradle.docker.tasks.container.DockerStartContainer) {
        dependsOn tasks.named('createContainer')
        targetContainerId tasks.named('createContainer').get().containerId
    }

    tasks.register('stopContainer', com.bmuschko.gradle.docker.tasks.container.DockerStopContainer) {
        targetContainerId tasks.named('createContainer').get().containerId
    }

    tasks.register('removeContainer', com.bmuschko.gradle.docker.tasks.container.DockerRemoveContainer) {
        targetContainerId tasks.named('createContainer').get().containerId
        dependsOn tasks.named('stopContainer')
        force = true
    }
}