pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.springframework.boot' version '3.3.0'
        id 'com.bmuschko.docker-remote-api' version '9.4.0'
    }
}


include 'etcd-sandbox'
include 'k8s-sandbox'
include 'eureka-server', 'eu-sandbox', 'eu-foo', 'eu-hello'
include 'zk-sandbox', 'zk-foo', 'zk-hello'
include 'consul-sandbox', 'consul-foo', 'consul-hello'

project(':consul-sandbox').projectDir = file('consul/sandbox')
project(':consul-hello').projectDir = file('consul/hello-service')
project(':consul-foo').projectDir = file('consul/foo-service')

project(':etcd-sandbox').projectDir = file('etcd/sandbox')
project(':k8s-sandbox').projectDir = file('k8s/sandbox')

project(':eureka-server').projectDir = file('eureka/eureka-server')
project(':eu-sandbox').projectDir = file('eureka/sandbox')
project(':eu-foo').projectDir = file('eureka/foo-service')
project(':eu-hello').projectDir = file('eureka/hello-service')

project(':zk-sandbox').projectDir = file('zookeeper/sandbox')
project(':zk-foo').projectDir = file('zookeeper/foo-service')
project(':zk-hello').projectDir = file('zookeeper/hello-service')