pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.springframework.boot' version '3.3.0'
        id 'com.bmuschko.docker-remote-api' version '9.4.0'
    }
}

include 'consulSpace:sandbox'
include 'consulSpace:consul-main'
include 'consulSpace:consul-translate'

include 'etcdSpace:sandbox'

include 'eurekaSpace:eureka'
include 'eurekaSpace:sandbox'
include 'eurekaSpace:eu-main'
include 'eurekaSpace:eu-translate'

include 'k8sSpace:clientSandbox'

include 'zookeeperSpace:hazelcastZkSpi'
include 'zookeeperSpace:sandbox'
include 'zookeeperSpace:zk-main'
include 'zookeeperSpace:zk-translate'

//project(':zk-sandbox').projectDir = file('zookeeperSpace/sandbox')
//project(':zk-hazelcast').projectDir = file('zookeeperSpace/hazelcastZkSpi')
//project(':zk-main').projectDir = file('zookeeperSpace/zk-main')
//project(':zk-translate').projectDir = file('zookeeperSpace/zk-translate')

include 'spring-config:config-server'
include 'spring-config:client'
//project(':config-server').projectDir = file('spring-config:config-server')
//project(':config-client').projectDir = file('spring-config:client')
