pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    plugins {
        id 'org.springframework.boot' version '3.3.0'
        id 'com.bmuschko.docker-remote-api' version '9.4.0'
    }
}

include 'consul:vkConsul'
include 'etcd:vkEtcd'
include 'eureka:eureka-server'
include 'eureka:foo-service'
include 'eureka:hello-service'
include 'k8s:vkK8s'
include 'zookeeper:foo-service'
include 'zookeeper:zkSandbox'
include 'zookeeper:hello-service'
include 'eureka:euSandbox'