plugins {
    id 'org.springframework.boot'
}

containerPorts = ["8080:8080"]
containerEnv = [
        "SPRING_PROFILES_ACTIVE": "docker",
        "EUREKA_URL": "http://eureka:8761/eureka"
]

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
