services:
  my-consul:
    image: hashicorp/consul:2.0.2
    restart: always
    ports:
      - "8500:8500"

  consul-translate:
    image: localhost:5000/consul-translate
    deploy:
      replicas: 3
    ports:
      - "18000:18080"
    environment:
      - SERVER_PORT=18000
      - SPRING_CLOUD_CONSUL_HOST=my-consul

  consul-main:
    image: localhost:5000/consul-main
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_CONSUL_HOST=my-consul