dependencies {
    implementation "org.apache.curator:curator-framework:${curatorVersion}"  // required for compatibility. Otherwise, 5.1.0 is used
    // workaround of absence of required version (4.1.105) of netty in maven central
//    implementation("io.netty:netty-transport-native-epoll:4.1.132.Final")

    implementation "com.hazelcast:hazelcast-zookeeper:4.0.2"
    implementation "com.hazelcast:hazelcast:5.2.1"
    runtimeOnly("commons-logging:commons-logging:1.3.5")

    api "org.apache.curator:curator-x-discovery:${curatorVersion}"
    testImplementation "org.apache.curator:curator-test:${curatorVersion}"

    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.8.2")
}
