apiVersion: apps/v1

kind: Deployment
metadata:
  name: vk-cloud-hello
  labels:
    app: k8s-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-hello
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
        - name: k8s-hello
          image: vladika/k8s-hello:latest
          ports:
            - containerPort: 8080