apiVersion: apps/v1

kind: Deployment
metadata:
  name: vk-cloud-hello
  labels:
    app: k8s-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-hello
  template:
    metadata:
      labels:
        app: k8s-hello
    spec:
      containers:
        - name: k8s-hello
          image: localhost:5000/k8s-hello:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: vk-cloud-hello
spec:
  selector:
    app: k8s-hello
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 8080  # container port your app listens on
  type: NodePort