#apiVersion: v1
#kind: Service
#metadata:
#  name: k8s-hello-service
#spec:
#  selector:
#    app: k8s-hello
#  ports:
#    - protocol: TCP
#      port: 80          # service port
#      targetPort: 8080  # container port your app listens on
#  type: NodePort