plugins {
    id 'org.springframework.boot'
}

containerPorts = ["8080:8080"]


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

//    implementation 'org.apache.httpcomponents.client5:httpclient5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
