
dependencies {
    // TRANSITIVE DEPENDENCY CONFLICT: Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/dsl/V1FlowControlAPIGroupDSL
//    api "io.fabric8:kubernetes-client:8.0.0"
//    api "io.fabric8:kubernetes-client:7.9.0"

    // 1. Import the Fabric8 BOM platform
    implementation platform('io.fabric8:kubernetes-client-bom:7.9.0')

    // 2. Import the client WITHOUT a version tag (it inherits 7.9.0 from the BOM)
    implementation 'io.fabric8:kubernetes-client'

    runtimeOnly "org.bouncycastle:bcprov-jdk18on:1.82"
    runtimeOnly "org.bouncycastle:bcpkix-jdk18on:1.82"
}
