# Eureka server URL(s) to register with
eureka.serviceUrl.default=http://localhost:8761/eureka/

# Time intervals and other settings
eureka.registryFetchIntervalSeconds=30

# Whether to register with Eureka
eureka.shouldRegisterWithEureka=true
eureka.shouldFetchRegistry=true
eureka.validateInstanceId=true

# Instance metadata settings
eureka.instance.appname=my-native-client
eureka.instance.ipAddress=127.0.0.1
eureka.instance.port=8080
eureka.instance.vipAddress=my-native-client

# Lease renewal interval (in seconds)
eureka.leaseRenewalIntervalInSeconds=10