

dependencies {
    implementation 'io.etcd:jetcd-core:0.8.6'
    implementation "com.fasterxml.jackson.core:jackson-databind:2.18.4"

    runtimeOnly "ch.qos.logback:logback-classic:1.5.21" // logging

//    testImplementation "org.testcontainers:toxiproxy${testContainersVersion}"
//    testImplementation "org.testcontainers:junit-jupiter${testContainersVersion}"
//    testImplementation "org.testcontainers:testcontainers${testContainersVersion}"

    testImplementation "org.testcontainers:testcontainers:2.0.2"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:2.0.2"

    implementation platform('org.testcontainers:testcontainers-bom:2.0.2') //import bom
    testImplementation('org.testcontainers:testcontainers-mysql') //no version specified
    testImplementation('org.testcontainers:testcontainers-postgresql') //no version specified


    //    implementation "org.junit.jupiter:junit-jupiter-params:${junitJupiterVersion}"
//    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation("org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}")

    runtimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}")
}
