#apiVersion: v1
#kind: Namespace
#metadata:
#  name: consul
#---
apiVersion: v1
kind: Service
metadata:
  name: consul
#  namespace: consul
spec:
  selector:
    app: consul
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: dns
      protocol: UDP
      port: 8600
      targetPort: 8600
    - name: server
      protocol: TCP
      port: 8300
      targetPort: 8300
    - name: serflan
      protocol: TCP
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: UDP
      port: 8301
      targetPort: 8301
    - name: serfwann
      protocol: TCP
      port: 8302
      targetPort: 8302
    - name: serfwann-udp
      protocol: UDP
      port: 8302
      targetPort: 8302
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
#  namespace: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: hashicorp/consul:2.0.2
          args:
            - "agent"
            - "-server"
            - "-bootstrap-expect=1"
            - "-ui"
            - "-client=0.0.0.0"
          ports:
            - containerPort: 8500  # HTTP UI/API
            - containerPort: 8600  # DNS
            - containerPort: 8300  # Server RPC
            - containerPort: 8301  # Serf LAN
            - containerPort: 8302  # Serf WAN
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data
      volumes:
        - name: consul-data
          emptyDir: {}
