apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-main
  template:
    metadata:
      labels:
        app: consul-main
    spec:
      containers:
        - name: consul-main
          image: consul-main:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul

---
apiVersion: v1
kind: Service
metadata:
  name: consul-main
spec:
  type: NodePort
  selector:
    app: consul-main
  ports:
    - port: 8080
      targetPort: 8080