apiVersion: v1
kind: Service
metadata:
  name: zk-main
  labels:
    app: zk-main
spec:
  type: {{ .Values.zkMain.service.type }}
  selector:
    app: zk-main
  ports:
    - name: http
      port: {{ .Values.zkMain.service.port }}
      targetPort: {{ .Values.zkMain.service.targetPort }}
