apiVersion: v1
kind: Service
metadata:
  name: zk-translate
  labels:
    app: zk-translate
spec:
  type: {{ .Values.zkTranslate.service.type }}
  selector:
    app: zk-translate
  ports:
    - name: http
      port: {{ .Values.zkTranslate.service.port }}
      targetPort: {{ .Values.zkTranslate.service.targetPort }}