
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  hello-service:
    image: eu-hello
    deploy:         # works only in swarm mode (docker stack deploy).
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "18000:18000"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=http://eureka:8761/eureka

  foo-service:
    image: eu-foo
    ports:
      - "18100:18100"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URL=http://eureka:8761/eureka