
services:
  vk-etcd:
    image: vk-etcd
    ports:
      - "2379:2379"
      - "2380:2380"

  etcd-sandbox:
    image: etcd-sandbox:latest
    deploy:
      replicas: 3
    ports:
      - "7777:7777"
    depends_on:
      - vk-etcd
    environment:
      - ETCD_ENDPOINT=http://vk-etcd:2379
